version: '3.5'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    depends_on:
      - backend
      - frontend

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example

  redis:
    image: redis
    ports:
      - 6379:6379

  backend:
    image: backend_example
    ports:
      - 8888:8000
    environment:
      - FRONT_URL=http://localhost:8889
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
      - DB_NAME=example
      - DB_HOST=db
    depends_on:
      - db
      - redis

  frontend:
    image: frontend_example
    ports:
      - 8889:5000
    environment:
      - API_URL=http://localhost:8888
