version: '3.5'

services:

  frontend:
    image: frontend
    ports:
      - 8889:5000

  backend:
    image: backend
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
      - DB_NAME=example
      - DB_HOST=db
    ports:
      - 8888:8000
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    container_name: db_container
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
